# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab1d04e9dd72019da5a9e36a6f9b5c6e7ca569fef99074c1dda68df383dab2b493e37d16fbeb4ca3ba9edb67987c6de2c687d2eddd14719656b194e3fcbf62a

test:
  secret_key_base: 40f7abce7fabf888c2aa03027eaa374d7d5d9d2d518a6def64c68cfb4391a32179b486a5bf34e3309f743a7cffe6b71cfd740475dbc4e14d50cd0ebad9ccccd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
